import subprocess
import json
import os
import sys
import time

# --- Configuration ---
# Define the paths for the files generated by the trend report script
ORIGINAL_JSON_REPORT = os.path.join('src', 'trends_report_jan_2026.json')
ORIGINAL_MD_REPORT = 'trends_report_jan_2026.md'
RUN_SCRIPT_NAME = "run_trend_report.py"

def cleanup_generated_files():
    """Deletes the report files created by the script to ensure a clean state."""
    print("...Cleaning up previous report files...")
    for f in [ORIGINAL_JSON_REPORT, ORIGINAL_MD_REPORT]:
        if os.path.exists(f):
            try:
                os.remove(f)
                print(f"   - Removed {f}")
            except OSError as e:
                print(f"   - WARNING: Could not remove {f}: {e}")

def run_and_capture(run_number: int, output_path: str):
    """Runs the trend report script and saves the output to a specified file."""
    print(f"--- Starting Run #{run_number} ---")
    
    # Ensure a clean state before running
    cleanup_generated_files()
    
    try:
        print(f"...Executing {RUN_SCRIPT_NAME}...")
        process = subprocess.run(
            [sys.executable, RUN_SCRIPT_NAME],
            capture_output=True,
            text=True,
            check=True,
            cwd=os.path.dirname(os.path.abspath(__file__)),
            encoding='utf-8' # Explicitly set encoding
        )
        print("...Script output...")
        print(process.stdout)
        if process.stderr:
            print("...Errors from script...")
            print(process.stderr)

        # Check if the original output file was created
        if os.path.exists(ORIGINAL_JSON_REPORT):
            # Move the generated report to the run-specific file
            os.rename(ORIGINAL_JSON_REPORT, output_path)
            print(f"SUCCESS: Run #{run_number} complete. Report saved to {output_path}\n")
            return True
        else:
            print(f"ERROR: The script '{RUN_SCRIPT_NAME}' did not generate the expected file '{ORIGINAL_JSON_REPORT}'.")
            return False

    except subprocess.CalledProcessError as e:
        print(f"ERROR: Failed to execute '{RUN_SCRIPT_NAME}' on run #{run_number}.")
        print(e.stdout)
        print(e.stderr)
        return False
    except FileNotFoundError:
        print(f"ERROR: Could not find '{ORIGINAL_JSON_REPORT}' to rename.")
        return False


def compare_reports(file1: str, file2: str):
    """Compares two JSON trend report files and prints the differences."""
    print("--- Comparing Reports ---")
    try:
        with open(file1, 'r', encoding='utf-8') as f:
            report1_data = json.load(f)
        with open(file2, 'r', encoding='utf-8') as f:
            report2_data = json.load(f)
    except (FileNotFoundError, json.JSONDecodeError) as e:
        print(f"Error reading or parsing report files: {e}")
        return

    # Extract the list of trends, which is under the "trends" key
    # The AI model generates "name", so we use that key for comparison.
    trends1 = {item['name'] for item in report1_data.get("trends", [])}
    trends2 = {item['name'] for item in report2_data.get("trends", [])}

    similarities = trends1.intersection(trends2)
    differences_in_run2 = trends2 - trends1  # New in run 2
    differences_in_run1 = trends1 - trends2  # Missing from run 2

    print(f"\nAnalysis Complete:")
    print(f"   - {len(similarities)} trends are consistent across both runs.")
    print(f"   - {len(differences_in_run2)} new trends appeared in Run #2.")
    print(f"   - {len(differences_in_run1)} trends from Run #1 did not appear in Run #2.\n")

    if similarities:
        print("Consistent Trends (Found in both runs):")
        for trend in sorted(list(similarities)):
            print(f"   - {trend}")
        print("")

    if differences_in_run2:
        print("New Trends (Only in Run #2):")
        for trend in sorted(list(differences_in_run2)):
            print(f"   - {trend}")
        print("")

    if differences_in_run1:
        print("Disappeared Trends (Only in Run #1):")
        for trend in sorted(list(differences_in_run1)):
            print(f"   - {trend}")
        print("")


def main():
    output1_path = "trend_report_run1.json"
    output2_path = "trend_report_run2.json"

    # Run the script twice
    run1_success = run_and_capture(1, output1_path)
    # Add a small delay to ensure file handles are released
    time.sleep(1) 
    run2_success = run_and_capture(2, output2_path)

    # Compare the results if both runs were successful
    if run1_success and run2_success:
        compare_reports(output1_path, output2_path)
    else:
        print("\nComparison skipped due to errors in one or both runs.")
        
    # Final cleanup of the temporary run files
    print("\n...Cleaning up temporary run files...")
    for f in [output1_path, output2_path]:
        if os.path.exists(f):
            os.remove(f)
            print(f"   - Removed {f}")


if __name__ == "__main__":
    main()
